AWSTemplateFormatVersion: "2010-09-09"
Description: Create EC2 environment

#### EC2 ####
Resources:
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-072bfb8ae2c884cc4
      InstanceType: t2.micro
      KeyName: xxxxxxxxxxxxxxxxxxxxxxxxxxx
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !ImportValue SubnetPublic1AId
          GroupSet:
            - !ImportValue SgPublicId
      IamInstanceProfile: !ImportValue InstanceProfileforEC2Id
      UserData: !Base64 |
        #!/bin/bash
        sudo su -
        yum update -y
        yum install -y docker
        systemctl start docker
        systemctl enable docker
        cd ~
        echo FROM nginx > Dockerfile
        AWS_ACCOUNT_ID=xxxxxxxxxxxxxxxxxxxxxxxxxxx
        aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com
        docker build -t ecr-rep .
        docker tag ecr-rep:latest ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/ecr-rep:latest
        docker push ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/ecr-rep:latest

      Tags:
        - Key: Name
          Value: Maintenance-Server
